language: node_js
node_js:
  - '6'
  - '8'
  - '10'
deploy:
  provider: npm
  email: nwoltman@outlook.com
  on:
    tags: true
  api_key:
    secure: bbLxm6hGK+bSVkdfRwDJWw5Y6m0zbpx2WLa4IP73gjpYeP9uEyFsMZI1T/yepoTb3p2eods9eHnGL1pEks4oYFEPUuxn4ZgnZMeODg8oSwd5+5lefH1UlZOkrzMf2wzUTMyLgZex/IQEHJcTWhGsSRRrpBj413nIlTIo10lIiBkSNI+FMDj0AlCIQw3fCpUwSx7wlCREKi49eqlsYyUKi6njeAflX85Xl4/UK/U66eQ234Hm8OH9PgtRndYPXWZexvL7KxJZt/GrqE+IA8/t4dg5JWgpp0c/pxgU7hBB3jEeymk94MT6Q4JNYNI54ZIaZPbdY1mnJHjSYwgS6/MbAF+0iAZC8PQruHdKY0stD0xN4XwZjPj8hHhWxWXxDU/ZxEApVQed2tB9CVBfDXxMvbWMNoyEYyU0QJJ5de5KkuW0kYyUWUgK4pzuh7tbgRhmNIwcvQhWf0DhzC32LUxOhpMYfgddrtrKd76GamPg7B2Ux0s6PWdmdyqG+UuKMRWYjsMR/Z5aZg0GZFNiRdZp3P4q9PD96tPw2hELS6VhG+8JzeBcB0dRKQIFq1WhG8u27TwY0dwuSq9RRPl+TEWJn4LQKc8VJFnQKTUNllKnuGz97P6xyRl6v/EGbE/kpl/KMWuCncJam1Ryl2ljZVXD1QEY0O9szEsBVnAP9JTJo5c=
